"""
    AbstractPhysicsSolver

Abstract base type for calculating the physical observables of a single cluster. This serves as a reference implementation of the NLCE algorithm and a test set to ensure that the clusters are generated correctly.

Subtypes must implement:
- `eigenvalues()` - eigenvalues of the cluster with respect to the model
- `eigenvectors()` - eigenvectors of the cluster with respect to the model
- `cluster_weights()` - NLCE weights of the cluster generated by Lincege.jl
"""
abstract type AbstractPhysicsSolver end

"""
    eigenvalues(solver::AbstractPhysicsSolver)

Return the energy eigenvalues of the solver's cluster Hamiltonian.
"""
eigenvalues(::AbstractPhysicsSolver) = _NI("eigenvalues")

"""
    eigenvectors(solver::AbstractPhysicsSolver)

Return the eigenvectors of the solver's cluster Hamiltonian.
"""
eigenvectors(::AbstractPhysicsSolver) = _NI("eigenvectors")

"""
    cluster_weights(solver::AbstractPhysicsSolver)

Return the NLCE weights of the solver's cluster as generated by Lincege.jl.
"""
cluster_weights(::AbstractPhysicsSolver) = _NI("cluster_weights")

"""
    observables(solver::AbstractPhysicsSolver, betas)

Compute the thermodynamic observables of the solver's cluster at each inverse
temperature in `betas`, returned as a `NamedTuple` of vectors `(energy,
specific_heat, entropy)`.
"""
function observables(solver::AbstractPhysicsSolver, betas::Vector{Float64})
        Es = eigenvalues(solver)
        Es2 = Es .^ 2
        boltzmanns = similar(Es)
        n = length(betas)
        energy = Vector{Float64}(undef, n)
        specific_heat = Vector{Float64}(undef, n)
        entropy = Vector{Float64}(undef, n)

        for (i, beta) in enumerate(betas)
                boltzmanns .= exp.(-beta .* Es)
                Z = sum(boltzmanns)
                e = dot(Es, boltzmanns) / Z
                energy[i] = e
                specific_heat[i] = beta^2 * (dot(Es2, boltzmanns) / Z - e^2)
                entropy[i] = log(Z) + beta * e
        end

        (energy=energy, specific_heat=specific_heat, entropy=entropy)
end

include("Ising.jl")
include("NLCE.jl")
include("Resummations.jl")
